[package]
name = "trade_game"
version = "0.1.0"
authors = ["Claire Robsahm <claire@chapien.net>"]

[features]
default = ["vulkan"]
vulkan = ["amethyst/vulkan"]
metal = ["amethyst/metal"]

[dependencies]
decimal = "2.0.4"

[dependencies.amethyst]
version = "0.15.0"
